// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRu5jHAFiqXFivBnqxe0evQlT1IGw2KTE',
    appId: '1:911034868406:ios:f2b6c2adc19c3d35fffc17',
    messagingSenderId: '911034868406',
    projectId: 'kiki-budget',
    storageBucket: 'kiki-budget.firebasestorage.app',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRu5jHAFiqXFivBnqxe0evQlT1IGw2KTE',
    appId: '1:911034868406:ios:f2b6c2adc19c3d35fffc17',
    messagingSenderId: '911034868406',
    projectId: 'kiki-budget',
    storageBucket: 'kiki-budget.firebasestorage.app',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZqqMl1uojT_YJlFsCYbMA3TAo6Jwfqa0',
    appId: '1:911034868406:web:b3b0c200fc183654fffc17',
    messagingSenderId: '911034868406',
    projectId: 'kiki-budget',
    authDomain: 'kiki-budget.firebaseapp.com',
    storageBucket: 'kiki-budget.firebasestorage.app',
    measurementId: 'G-CQ9H1348ZX',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZqqMl1uojT_YJlFsCYbMA3TAo6Jwfqa0',
    appId: '1:911034868406:web:b3b0c200fc183654fffc17',
    messagingSenderId: '911034868406',
    projectId: 'kiki-budget',
    authDomain: 'kiki-budget.firebaseapp.com',
    storageBucket: 'kiki-budget.firebasestorage.app',
    measurementId: 'G-CQ9H1348ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Xpbjc6Jhilm58UvCC-ukhw1kmneTcwM',
    appId: '1:911034868406:android:a792ee7f000725d4fffc17',
    messagingSenderId: '911034868406',
    projectId: 'kiki-budget',
    storageBucket: 'kiki-budget.firebasestorage.app',
  );

}